name: PHPUnit

on:
  push:
  pull_request:

jobs:

  tests:
    name: Tests

    strategy:
      matrix:
        include:
          - php: '8.1'
          - php: '7.4'
      fail-fast: false

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, json
          tools: php-cs-fixer, phpunit
          coverage: pcov
      
      - name: Install dependencies
        run: composer install

      - name: Test
        run: composer check